import { precacheAndRoute, cleanupOutdatedCaches } from 'workbox-precaching';

// Clear old caches on activation
cleanupOutdatedCaches();

// Precache assets generated by VitePWA (will be injected at build time)
precacheAndRoute(self.__WB_MANIFEST || []);

// Force immediate activation of new service worker
self.addEventListener('install', (event) => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(self.clients.claim());
});

self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only intercept image requests
  if (request.destination !== 'image') return;

  const acceptHeader = request.headers.get('accept') || '';
  // Determine best alternative: AVIF first, then WebP
  const supportsAvif = acceptHeader.includes('image/avif');
  const supportsWebp = acceptHeader.includes('image/webp');
  if (!supportsAvif && !supportsWebp) return;

  const url = new URL(request.url);
  // Only handle .png / .jpg / .jpeg that live under /images/ (or any path)
  if (!url.pathname.match(/\.(png|jpe?g)$/i)) return;

  const basePath = url.pathname
    .replace(/\.(png|jpe?g)$/i, '');

  const tryFormats = [];
  if (supportsAvif) tryFormats.push({ dir: 'images-avif', ext: '.avif' });
  if (supportsWebp) tryFormats.push({ dir: 'images-webp', ext: '.webp' });

  const attemptFetch = (index) => {
    if (index >= tryFormats.length) return fetch(request);
    const { dir, ext } = tryFormats[index];
    // Construct path: /images-avif/original/path/file.avif
    // e.g. /textures/planet.png -> /images-avif/textures/planet.avif
    const altPath = `/${dir}${basePath}${ext}`;
    const altRequest = new Request(url.origin + altPath, request);
    return fetch(altRequest).then(r => (r.ok ? r : attemptFetch(index + 1)))
      .catch(() => attemptFetch(index + 1));
  };

  event.respondWith(attemptFetch(0));
}); 